SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'A%' AND (CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u')
UNION 
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'E%' AND (CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u')
UNION
SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'I%' AND (CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u')
UNION
SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'O%' AND (CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u')
UNION
SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'U%' AND (CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u')
